# Generated by Django 3.1.14 on 2022-07-04 16:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelname', models.CharField(help_text=' Name of car car model', max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text=' Name of car manufacturer', max_length=50)),
                ('country', models.CharField(help_text=' origin ', max_length=50, verbose_name='base country')),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text=' Name of supplier', max_length=50)),
                ('country', models.CharField(help_text=' scountry of supplier ', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Part',
            fields=[
                ('part_number', models.CharField(help_text='unique part number required', max_length=50, primary_key=True, serialize=False)),
                ('description', models.CharField(help_text='part description', max_length=50)),
                ('car_model', models.ManyToManyField(to='car.CarModel')),
                ('supplier', models.ForeignKey(default='none', on_delete=django.db.models.deletion.SET_DEFAULT, related_name='supplier_name', to='car.supplier')),
            ],
        ),
        migrations.AddField(
            model_name='carmodel',
            name='manufacturer',
            field=models.ForeignKey(help_text=' cannot be deleted', on_delete=django.db.models.deletion.RESTRICT, to='car.manufacturer'),
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('reg', models.CharField(help_text='registration plate number', max_length=50, primary_key=True, serialize=False)),
                ('manufacturer', models.CharField(max_length=50)),
                ('colour', models.CharField(choices=[('c1', 'Blue'), ('c2', 'Red'), ('c4', 'Orange'), ('c3', 'Green')], max_length=2, verbose_name='car colour')),
                ('body', models.CharField(max_length=50)),
                ('price', models.IntegerField(null=True)),
                ('year', models.IntegerField(choices=[('Est', 'Estate'), ('Sal', 'Saloon'), ('Hatch', 'HatchBack'), ('Van', 'Van')], help_text=' year of production', verbose_name='made in year')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='car.carmodel', verbose_name='CarModel')),
            ],
        ),
    ]
