# Generated by Django 3.1.14 on 2022-07-07 17:51

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0003_auto_20220704_1926'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='car',
            managers=[
                ('a_cars', django.db.models.manager.Manager()),
            ],
        ),
    ]
