# Generated by Django 3.1.14 on 2022-07-07 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0006_auto_20220707_1910'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='car',
            managers=[
            ],
        ),
    ]
