# Generated by Django 3.1.14 on 2022-07-07 18:36

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0007_auto_20220707_1912'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='carmodel',
            managers=[
                ('bmw_cars', django.db.models.manager.Manager()),
            ],
        ),
    ]
