# Generated by Django 3.1.14 on 2022-07-07 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0009_auto_20220707_1941'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='carmodel',
            managers=[
            ],
        ),
    ]
